
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COL LPAREN RANGE ROW RPAREN SEP\n        expression : range SEP expression\n        \n        expression : range\n        \n        range : rows cols\n        \n        range : rows\n        \n        range : cols\n        \n        rows : ROW\n        \n        cols : COL\n        \n        rows : LPAREN row_exp RPAREN\n        \n        cols : LPAREN col_exp RPAREN\n        \n        row_exp : ROW SEP row_exp\n                | ROW RANGE ROW\n        \n        col_exp : COL SEP col_exp\n                | COL RANGE COL\n        \n        row_exp : ROW\n        \n        col_exp : COL\n        '
    
_lr_action_items = {'ROW':([0,6,8,18,19,],[5,13,5,13,23,]),'LPAREN':([0,3,5,8,16,],[6,10,-6,6,-8,]),'COL':([0,3,5,6,8,10,16,20,21,],[7,7,-6,14,7,14,-8,14,25,]),'$end':([1,2,3,4,5,7,9,15,16,17,],[0,-2,-4,-5,-6,-7,-3,-1,-8,-9,]),'SEP':([2,3,4,5,7,9,13,14,16,17,],[8,-4,-5,-6,-7,-3,18,20,-8,-9,]),'RPAREN':([11,12,13,14,22,23,24,25,],[16,17,-14,-15,-10,-11,-12,-13,]),'RANGE':([13,14,],[19,21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,8,],[1,15,]),'range':([0,8,],[2,2,]),'rows':([0,8,],[3,3,]),'cols':([0,3,8,],[4,9,4,]),'row_exp':([6,18,],[11,22,]),'col_exp':([6,10,20,],[12,12,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> range SEP expression','expression',3,'p_expression','pad_lexer.py',120),
  ('expression -> range','expression',1,'p_expression_range','pad_lexer.py',132),
  ('range -> rows cols','range',2,'p_range','pad_lexer.py',144),
  ('range -> rows','range',1,'p_range_no_cols','pad_lexer.py',150),
  ('range -> cols','range',1,'p_range_no_rows','pad_lexer.py',157),
  ('rows -> ROW','rows',1,'p_range_rows','pad_lexer.py',164),
  ('cols -> COL','cols',1,'p_range_cols','pad_lexer.py',170),
  ('rows -> LPAREN row_exp RPAREN','rows',3,'p_range_rows_grouped','pad_lexer.py',176),
  ('cols -> LPAREN col_exp RPAREN','cols',3,'p_range_cols_grouped','pad_lexer.py',182),
  ('row_exp -> ROW SEP row_exp','row_exp',3,'p_range_row_exp','pad_lexer.py',188),
  ('row_exp -> ROW RANGE ROW','row_exp',3,'p_range_row_exp','pad_lexer.py',189),
  ('col_exp -> COL SEP col_exp','col_exp',3,'p_range_col_exp','pad_lexer.py',198),
  ('col_exp -> COL RANGE COL','col_exp',3,'p_range_col_exp','pad_lexer.py',199),
  ('row_exp -> ROW','row_exp',1,'p_range_row','pad_lexer.py',208),
  ('col_exp -> COL','col_exp',1,'p_range_col','pad_lexer.py',214),
]
